
name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: iterative/setup-dvc@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2     
    - name: Pull from dvc
      run:  |
        dvc remote list
        dvc remote modify mys3remote url s3://udas3bucket
        dvc remote modify mys3remote endpointurl https://udas3bucket.s3.amazonaws.com/
        dvc remote modify mys3remote read_timeout 500
        dvc remote modify mys3remote connect_timeout 500
        dvc remote modify mys3remote region us-east-2
        dvc remote modify mys3remote access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        dvc remote modify mys3remote secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        dvc doctor
        dvc push
        aws s3 ls s3://udas3bucket/
        dvc pull -vv --remote mys3remote
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install flake8 pytest
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name base
    - name: Lint with flake8
      run: |
        $CONDA/bin/conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        $CONDA/bin/flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        # stop the build if there are Python syntax errors or undefined names
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        #flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
 
    - name: Test with pytest
      run: |
        $CONDA/bin/pytest


